#!/usr/bin/env python3
"""Bake 16x16 PNG sprites into static C arrays (ABGR format for sr_sprites.h).
Replaces png2sprite.c for environments without stb_image compiled."""
import struct, zlib, os, sys

def read_png_pixels(filename):
    """Read a 16x16 RGBA PNG and return list of (r,g,b,a) tuples."""
    with open(filename, 'rb') as f:
        data = f.read()

    # Verify PNG signature
    assert data[:8] == b'\x89PNG\r\n\x1a\n', f"Not a PNG: {filename}"

    # Parse chunks to find IHDR and IDAT
    pos = 8
    width = height = 0
    idat_data = b''
    while pos < len(data):
        length = struct.unpack('>I', data[pos:pos+4])[0]
        ctype = data[pos+4:pos+8]
        chunk_data = data[pos+8:pos+8+length]
        pos += 12 + length  # 4 len + 4 type + data + 4 crc

        if ctype == b'IHDR':
            width, height = struct.unpack('>II', chunk_data[:8])
            bit_depth = chunk_data[8]
            color_type = chunk_data[9]
            assert width == 16 and height == 16, f"{filename}: {width}x{height}, need 16x16"
            assert bit_depth == 8 and color_type == 6, f"{filename}: need 8-bit RGBA"
        elif ctype == b'IDAT':
            idat_data += chunk_data
        elif ctype == b'IEND':
            break

    # Decompress
    raw = zlib.decompress(idat_data)

    # Parse scanlines (filter byte + 4 bytes per pixel * 16 pixels = 65 bytes per row)
    pixels = []
    stride = 1 + width * 4
    for y in range(height):
        row_start = y * stride
        filt = raw[row_start]
        row_data = bytearray(raw[row_start+1:row_start+stride])

        # Apply PNG filter reconstruction
        if filt == 0:  # None
            pass
        elif filt == 1:  # Sub
            for i in range(4, len(row_data)):
                row_data[i] = (row_data[i] + row_data[i-4]) & 0xFF
        elif filt == 2:  # Up
            if y > 0:
                prev_start = (y-1) * stride + 1
                prev_row = raw[prev_start:prev_start+width*4]
                for i in range(len(row_data)):
                    row_data[i] = (row_data[i] + prev_row[i]) & 0xFF
        elif filt == 3:  # Average
            prev_start = (y-1) * stride + 1 if y > 0 else None
            for i in range(len(row_data)):
                a = row_data[i-4] if i >= 4 else 0
                b = raw[prev_start+i] if prev_start is not None else 0
                row_data[i] = (row_data[i] + (a + b) // 2) & 0xFF
        elif filt == 4:  # Paeth
            prev_start = (y-1) * stride + 1 if y > 0 else None
            for i in range(len(row_data)):
                a = row_data[i-4] if i >= 4 else 0
                b = raw[prev_start+i] if prev_start is not None else 0
                c = raw[prev_start+i-4] if (prev_start is not None and i >= 4) else 0
                p = a + b - c
                pa, pb, pc = abs(p-a), abs(p-b), abs(p-c)
                if pa <= pb and pa <= pc: pr = a
                elif pb <= pc: pr = b
                else: pr = c
                row_data[i] = (row_data[i] + pr) & 0xFF

        for x in range(width):
            off = x * 4
            r, g, b, a = row_data[off], row_data[off+1], row_data[off+2], row_data[off+3]
            pixels.append((r, g, b, a))

    return pixels


def rgba_to_abgr(r, g, b, a):
    """Convert RGBA to ABGR uint32."""
    if a < 128:
        return 0x00000000
    return (a << 24) | (b << 16) | (g << 8) | r


def bake_sprite(png_path, var_name, out):
    """Convert one PNG to a C array."""
    pixels = read_png_pixels(png_path)
    out.write(f"static const uint32_t {var_name}[SPR_W * SPR_H] = {{\n")
    for y in range(16):
        out.write("    ")
        for x in range(16):
            r, g, b, a = pixels[y * 16 + x]
            abgr = rgba_to_abgr(r, g, b, a)
            out.write(f"0x{abgr:08X},")
        out.write("\n")
    out.write("};\n\n")
    print(f"  baked {png_path} -> {var_name}")


if __name__ == '__main__':
    sprite_dir = os.path.join(os.path.dirname(__file__), '..', 'assets', 'sprites')
    src_dir = os.path.join(os.path.dirname(__file__), '..', 'src')

    # ── Bake card sprites ──
    card_out_path = os.path.join(src_dir, 'sr_card_sprites.h')
    with open(card_out_path, 'w') as out:
        out.write("/* Auto-generated card art sprites (ABGR format).\n")
        out.write(" * Generated by utilities/bake_sprites.py — do not edit by hand. */\n\n")
        out.write("#ifndef SR_CARD_SPRITES_H\n#define SR_CARD_SPRITES_H\n\n")

        card_names = [
            ("card_shield.png",      "spr_card_shield"),
            ("card_shoot.png",       "spr_card_shoot"),
            ("card_burst.png",       "spr_card_burst"),
            ("card_move.png",        "spr_card_move"),
            ("card_melee.png",       "spr_card_melee"),
            ("card_overcharge.png",  "spr_card_overcharge"),
            ("card_repair.png",      "spr_card_repair"),
            ("card_stun.png",        "spr_card_stun"),
            ("card_fortify.png",     "spr_card_fortify"),
            ("card_double_shot.png", "spr_card_double_shot"),
            ("card_dash.png",        "spr_card_dash"),
            ("card_ice.png",         "spr_card_ice"),
            ("card_acid.png",        "spr_card_acid"),
            ("card_fire.png",        "spr_card_fire"),
            ("card_lightning.png",   "spr_card_lightning"),
            ("card_sniper.png",      "spr_card_sniper"),
            ("card_shotgun.png",     "spr_card_shotgun"),
            ("card_welder.png",      "spr_card_welder"),
            ("card_chainsaw.png",    "spr_card_chainsaw"),
            ("card_laser.png",       "spr_card_laser"),
            ("card_deflector.png",   "spr_card_deflector"),
            ("card_stun_gun.png",    "spr_card_stun_gun"),
        ]

        for png_name, var_name in card_names:
            bake_sprite(os.path.join(sprite_dir, png_name), var_name, out)

        # Lookup table indexed by card type enum
        out.write("/* Lookup table indexed by card type enum */\n")
        out.write("static const uint32_t *spr_card_table[] = {\n")
        for _, var_name in card_names:
            out.write(f"    {var_name},\n")
        out.write("};\n\n")
        out.write("#endif /* SR_CARD_SPRITES_H */\n")

    print(f"Wrote {card_out_path}")

    # ── Bake character sprites (engineer, scientist) ──
    # These get appended to a separate header that can be included
    char_out_path = os.path.join(src_dir, 'sr_char_sprites.h')
    with open(char_out_path, 'w') as out:
        out.write("/* Auto-generated character sprites (ABGR format).\n")
        out.write(" * Generated by utilities/bake_sprites.py — do not edit by hand. */\n\n")
        out.write("#ifndef SR_CHAR_SPRITES_H\n#define SR_CHAR_SPRITES_H\n\n")

        char_sprites = [
            ("engineer.png",  "spr_engineer_baked"),
            ("scientist.png", "spr_scientist_baked"),
        ]

        for png_name, var_name in char_sprites:
            bake_sprite(os.path.join(sprite_dir, png_name), var_name, out)

        out.write("#endif /* SR_CHAR_SPRITES_H */\n")

    print(f"Wrote {char_out_path}")
